INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'We may sometimes encounter an error that we cannot select the company in creating ticket, what is the "key" that we must not add to avoid this error?', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Capital letters', 3), (2, LAST_INSERT_ID(), 'B', 'b. Enter', 3), (2, LAST_INSERT_ID(), 'C', 'c. Shift Enter', 3), (2, LAST_INSERT_ID(), 'D', 'd. Special Character', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', "Where can we check Adv replacement customer's Tester entitlement or contract?", 'D', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. IB inquiry', 3), (2, LAST_INSERT_ID(), 'B', 'b. Dropbox, Splus, PIP', 3), (2, LAST_INSERT_ID(), 'C', 'c. Splus file, IB, Dropbox', 3), (2, LAST_INSERT_ID(), 'D', 'd. IB Inquiry, Service Manager Dashboard', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'Which UPS email ID is wrong?', 'D', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. emeabsc@ups.com', 3), (2, LAST_INSERT_ID(), 'B', 'b. upsapacclarkecallcenter@ups.com', 3), (2, LAST_INSERT_ID(), 'C', 'c. splsupport@ups.com', 3), (2, LAST_INSERT_ID(), 'D', 'd. none of the above', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'For escalated tickets, which of the following do we need to do in order to close the ticket?', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Escalate to NI > Send notification to customer and PM > Cancel the ticket', 3), (2, LAST_INSERT_ID(), 'B', 'b. Escalate first to customer and also inform the PM > Send the escalation info to NI> Click closed ticket. ', 3), (2, LAST_INSERT_ID(), 'C', 'c. Escalate to NI > Send notification to customer and PM > Cancel the ticket > Add the reason for cancellation', 3), (2, LAST_INSERT_ID(), 'D', 'b. Escalate to NI > Send notification to customer and PM > Click closed ticket > Select the reason for Closing.', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'What is the SLA for sending email to UPS?', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. 24 hours ', 3), (2, LAST_INSERT_ID(), 'B', 'b. 1 hour', 3), (2, LAST_INSERT_ID(), 'C', 'c. depends on the customer', 3), (2, LAST_INSERT_ID(), 'D', 'd. 30 minutes', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'Where can we check if the customer has provided incomplete details like Failed SN, Tester PN', 'A', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. IB inquiry', 3), (2, LAST_INSERT_ID(), 'B', 'b. PIP', 3), (2, LAST_INSERT_ID(), 'C', 'c. Splus file', 3), (2, LAST_INSERT_ID(), 'D', 'd. Dropbox', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'If the ticket is escalated manually through mpc e-mail, which of the following allows you to close the ticket on the tracker?', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Send to any email ID that ends ni.com through tracker and proceed to close the ticket', 3), (2, LAST_INSERT_ID(), 'B', 'b. Send to any email ID that ends ni.com through tracker and proceed to cancel the ticket', 3), (2, LAST_INSERT_ID(), 'C', 'c. Send escalation email again through tracker and proceed to cancel the ticket.', 3), (2, LAST_INSERT_ID(), 'D', 'd. Send to any MPC email ID through the tracker then proceed to close the ticket', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'Which of the following are we going to do if we need to check the item details that are to be shipped by UPS?', 'A', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Login to UPS and select order history', 3), (2, LAST_INSERT_ID(), 'B', 'b. Ask the customer once they received the item', 3), (2, LAST_INSERT_ID(), 'C', 'c. Call or email UPS about the details', 3), (2, LAST_INSERT_ID(), 'D', 'd. Use the snipped information from the Inventory you have captured before creating the ticket', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'In sending report to SPOC, what is our SLA?', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Within the day of upon receipt of the request from customer', 3), (2, LAST_INSERT_ID(), 'B', 'b. Within 1 hour', 3), (2, LAST_INSERT_ID(), 'C', 'c. Within 24 hours', 3), (2, LAST_INSERT_ID(), 'D', 'd. After POD update', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'Which of the following escalation process we do select on the Tracker', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Escalate to NI > Escalate to PM', 3), (2, LAST_INSERT_ID(), 'B', 'b. Escalation to PM> Escalation to NI', 3), (2, LAST_INSERT_ID(), 'C', 'c. Escalate to NI > Notification of escalation to customer', 3), (2, LAST_INSERT_ID(), 'D', 'd. Escalation to PM > Notification of escalation to customer', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'We have account numbers use, how many are those active?', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a.      5', 3), (2, LAST_INSERT_ID(), 'B', 'b.    3', 3), (2, LAST_INSERT_ID(), 'C', 'c.       4', 3), (2, LAST_INSERT_ID(), 'D', 'd.      2', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'When sending order to UPS, which of the e-mail ID do we need to include?', 'D', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. UPS / customer / NI global', 3), (2, LAST_INSERT_ID(), 'B', 'b. UPS / NI global / PM', 3), (2, LAST_INSERT_ID(), 'C', 'c. Requestor / PM / NI global', 3), (2, LAST_INSERT_ID(), 'D', 'd. NI global / Sir Noel / UPS', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'The customer in Bulgaria is requesting for an advance replacement, what is the warehouse code?', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. WPX1', 3), (2, LAST_INSERT_ID(), 'B', 'b. WMST2', 3), (2, LAST_INSERT_ID(), 'C', 'c. WMX3', 3), (2, LAST_INSERT_ID(), 'D', 'd. WSIN1', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'Which of the following shows part revision', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. 148495B-01L (01L)', 3), (2, LAST_INSERT_ID(), 'B', 'b. 148495B-01L (B)', 3), (2, LAST_INSERT_ID(), 'C', 'c. Both a and b', 3), (2, LAST_INSERT_ID(), 'D', 'd. PXIE-6571', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'What is the email address of SPOC team for RMA report?', 'A', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. sts.operations@ni.com', 3), (2, LAST_INSERT_ID(), 'B', 'b. STS.Service@ni.com', 3), (2, LAST_INSERT_ID(), 'C', 'c. sts.operationservice@ni.com', 3), (2, LAST_INSERT_ID(), 'D', 'd. sts.operation@ni.com', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'What indicates "length" in cable PN 141135B-32', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. B', 3), (2, LAST_INSERT_ID(), 'B', 'b. 32', 3), (2, LAST_INSERT_ID(), 'C', 'c. 35B', 3), (2, LAST_INSERT_ID(), 'D', 'd. 141135', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'What will you do if Part item requested by customer is not available in UPS and there is no revision?', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Look for the PN in other region (warehouse)', 3), (2, LAST_INSERT_ID(), 'B', 'b. Ask customer how to proceed', 3), (2, LAST_INSERT_ID(), 'C', 'c. Ask PM for an alternate PN and check the availability', 3), (2, LAST_INSERT_ID(), 'D', 'd. Call your supervisor', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'What warehouse code can we use for China requests?', 'D', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. WSHAA, WCTU2', 3), (2, LAST_INSERT_ID(), 'B', 'b. WCTU2, WNRT', 3), (2, LAST_INSERT_ID(), 'C', 'c. WKUL1, WSHA4', 3), (2, LAST_INSERT_ID(), 'D', 'd. WCTU2, WSHA4', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'What is the login username that we use for UPS?', 'D', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. alcaraz melody', 3), (2, LAST_INSERT_ID(), 'B', 'b. melody_alcaras', 3), (2, LAST_INSERT_ID(), 'C', 'c. alcaraz_melody', 3), (2, LAST_INSERT_ID(), 'D', 'd. melody_alcaraz', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', 'We need to send RMA report to sts.service@ni.com and On-site report to sts.operations@ni.com', 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', 'We use melody_alcaraz in checking part items in all warehouse including Canada', 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', 'The customer has returned back the received unit to its original box and sealed it again as according to them their old unit is now working. Is it okay to return it back to warehouse?', 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', 'SPOC means Single Person of Contact', 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', 'Different types of STS are T1, T2 and T3', 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', 'We are not required to send Adv Replacement within 4 hours', 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', 'RMA (Return Merchandize Agreement)- purpose of the report is to monitor which item in the warehouse was ordered and NI can supply back the item in warehouse', 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'True/False', "For NXP MY, we don't indicate the PO# in Order to UPS email for shipping instruction as UPS MY already know about this.", 'False', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'True', 3), (2, LAST_INSERT_ID(), 'B', 'False', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'Where can we check revisions for the requested item other than UPS site?', 'A', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Services Manager Dashboard', 3), (2, LAST_INSERT_ID(), 'B', 'b. Dropbox', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'Tell us the steps of how can we find the Part number revision in Splus/UPS site?', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Call UPS to ask for available PN', 3), (2, LAST_INSERT_ID(), 'B', 'b. Open Splus excel > Ctrl F > copy the number before the "letter" > Enter. Take note of the revision PN and go to UPS site, select the correct account, warehouse and search PN', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', "The customer did not provide the Tester SN and only indicates Pxie-xxxx on their request for Adv replacement. How will you find the failed PN and what will you do when you find the equivalent PN?", 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', "a. Ask the customer to provide the Failed PN, unless they provide the PN, we can't proceed with the order process", 3), (2, LAST_INSERT_ID(), 'B', 'b. Call UPS and ask for the PN of the model number that was provided by the customer', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', "If the ticket is for escalation, do we still need the new part details to be entered? Y/N and why", 'D', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Yes, we enter new part details with the same info on their previous order', 3), (2, LAST_INSERT_ID(), 'B', 'b. Yes, we enter new part details with the same info of failed pn and sn', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'What is the meaning of RMA?', 'A', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Return Merchandise Authorization', 3), (2, LAST_INSERT_ID(), 'B', 'b. Report Merchandise Authorization', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'STS T4 can accomodate how many slots?', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a.18 slots', 3), (2, LAST_INSERT_ID(), 'B', 'b. 36 slots', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'If you have created 2 tickets under the same customer, how many times do we need to send an e-mail to UPS?', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. We send e-mail twice because we have two tickets for the same customer', 3), (2, LAST_INSERT_ID(), 'B', 'b. We send email once for 2 tickets because we have the same customer', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', "If the UPS can't commit to the requested ETA, what will you do?", 'A', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Ask UPS first for higher service to meet the requested ETA even when the cost is expensive than usual - if it is really impossible due to distance inform customer of the earliest possible ETA', 3), (2, LAST_INSERT_ID(), 'B', 'b. Just agree to UPS when they said they cannot commit with the requested ETA, courier knows better', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'We have Tester#1 PN/SN (860985-01/PA1447993), Tester#2 PN/SN (860985-01/PA1829582), Tester#3 PN/SN (860985-01/PA1683511), Tester#4 (860985-01/PA1911773), Tester#5 (860985-01/PA1911773), Tester#6 (860985-01/PA1447993), Tester#7 (860985-01/PA1829582) - how many ticket do we need to create? and why?', 'D', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. 7 ticket as equivalent for 7 SN provided by customer', 3), (2, LAST_INSERT_ID(), 'B', 'b. 1 ticket as this is coming from one customer', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'When cancelling tickets, reasons are need to be selected- give atleast two', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Customer is eligible', 3), (2, LAST_INSERT_ID(), 'B', 'b. No stock in UPS, NI will process', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'The order has already been ordered to UPS, 1-hr has passed and no confirmation yet on the SO#, what will you do?', 'C', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. We wait until the UPS provide the SO# and only then we inform the customer', 3), (2, LAST_INSERT_ID(), 'B', 'b. We ask the PM to coordinate with the customer and inform that the SO# is not yet received', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', "The customer didn't received yet the order on the promised ETA, what will be your action?", 'A', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Ask UPS the reason of the delay and document it to our ticket, also inform customer of the reason and new ETA', 3), (2, LAST_INSERT_ID(), 'B', 'b. Inform customer the new ETA as per UPS', 3);
INSERT INTO exam_question (examid, question_type, question, answer, tech_id) VALUES (2, 'multiple choice', 'While on process, what are you going to do if email template in our tracker is not showing?', 'B', 3);																					INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, LAST_INSERT_ID(), 'A', 'a. Ask Sir Ferds to fix it first before you proceed th process', 3), (2, LAST_INSERT_ID(), 'B', 'b. Send manual email by copying from our previous emails and change the necessary details', 3);




INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 178, 'C', 'a. Splus', 3), (2, 178, 'D', 'd. IB Inquiry', 3);

INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 179, 'C', 'c. Open Splus excel > Ctrl F > copy the number after the "letter" rev > Enter. Take note of the revision PN and go to UPS site, select the correct account, warehouse and search PN', 3), (2, 179, 'D', 'd. Check with customer alternate PN', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 180, 'C', 'c. Check Splus 29620/dropbox, click ctrl+F and paste model number and search. When PN found, confirm with NI PM if the PN is correct.', 3), (2, 180, 'D', 'd. We inform the PM that we will be escalating their order request as it is not possible for us to order part with only the model number provided', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 181, 'C', 'c. No, because NI will enter details for it', 3), (2, 181, 'D', 'd. No, because there is no new part details to enter', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 182, 'C', 'c. Report Merchandise Agreement', 3), (2, 182, 'D', 'd. Return Merchandise Agreement', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 183, 'C', 'c. 72 slots', 3), (2, 183, 'D', 'd. 54 slots', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 184, 'C', 'c. We send email twice for the same order part info', 3), (2, 184, 'D', 'd. We send email once for same order part info', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 185, 'C', 'c. Ask the PM to coordinate directly with the UPS, since it is between NI and UPS whatever they have agreed on will be fine', 3), (2, 185, 'D', 'd. Inform the customer that the requested ETA is not possible and we just need to follow whatever ETA the UPS has given', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 186, 'C', 'c. 1 ticket as to gather all the information in one RMA', 3), (2, 186, 'D', 'd. 4 tickets as there are four Tester SN', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 187, 'C', 'c. Order was cancelled by the UPS', 3), (2, 187, 'D', 'd. No stock in UPS, customer will process', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 188, 'C', 'c. Send an hourly update to customer and inform that we are still coordinating with the UPS and will advise when the SO# is received', 3), (2, 188, 'D', 'd. We ask the UPS that as soon as the SO# is created, inform right away the consignee on the SO#', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 189, 'C', 'c. Ask PM to relay to customer of the changes', 3), (2, 189, 'D', 'd. Force UPS to deliver the item to customer with the initial agreed ETA', 3);
INSERT INTO exam_option (examid, questionid, option_letter, descrip, tech_id) VALUES (2, 190, 'C', 'c. Find the error for causing the Tracker not showing the template', 3), (2, 190, 'D', 'c. Wait for the template to be fixed in tracker', 3);
